import {ROLES} from '../../authorizer/roles.js';

export const IMAGE_LEVELS = [
    {
        level: 'mine',
        scope: 'SELF',
        label: 'My Images',
        requiresRole: null,
        description: 'Images you have generated. Rename them for easier recognition, or delete the ones you no longer need.'
    },
    {
        level: 'admin',
        scope: 'ADMIN',
        label: 'All Images',
        requiresRole: ROLES.IMAGE_ADMIN,
        description: 'Every image generated by any user. Filter by user to review a single account.'
    }
];

export const DEFAULT_IMAGE_LEVEL = 'mine';

export const findImageLevel = (level) => {
    return IMAGE_LEVELS.find((imageLevel) => imageLevel.level === level) ?? null;
};

export const visibleImageLevels = (hasRole) => {
    return IMAGE_LEVELS.filter((imageLevel) => {
        if (!imageLevel.requiresRole) {
            return true;
        }

        return hasRole(imageLevel.requiresRole);
    });
};
