server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(jpg|jpeg|png|gif|css|js|woff2?|ttf|eot|svg|webp)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri $uri/ =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}